### ISSUE TITLE
Not working with v2 (EIP-1559)

### ISSUE THREAD

**Issue by hcminh225** [abdk-consulting/abdk-toolkit#2]
Hello dev team.
I tried to recover address from the raw transaction but it was successful. I got 'invalid rlp data':
Here is transaction hash: 0xb1ce4c8e294e5e1dead3a78a9966f04ded8e43b3fc99275f8dcfc33ad3e33d66
and raw transaction
0x02f874018402319fbb8085114852d5038303d09094519db590b38dde562ea9e13c265df22a606821d38801608dbad20ea35980c001a0be58a22807468ec140519d1270acce56a8596b0c8adb06d3b2d5252e80230fe2a01f4f6b6be980b0a8e393a1b54c7f61680d95f4e80bee78e73fd4379318ad3faf
https://etherscan.io/getRawTx?tx=0xb1ce4c8e294e5e1dead3a78a9966f04ded8e43b3fc99275f8dcfc33ad3e33d66
If I did it wrong can you guide me to do it right?
Thank you

**Comment by DubbaThony** [comment]
You didn't do anything wrong. With new transactions, there is additional byte at the beginning telling you transaction type.
Currently there are 3 transaction types that you can differentiate with presence/value of it:
- legacy
- dynamic fee (eip-1559)
- envelope / access list transaction

**Comment by 3sGgpQ8H** [comment]
EIP-1559 support implemented, but without access lists.
